---
extends: default

# yamllint disable rule:line-length

rules:
  line-length:
    max: 100
  colons: enable
  indentation:
    level: warning
    # Require indentation https://redhat-cop.github.io/automation-good-practices/#_yaml_and_jinja2_syntax
    indent-sequences: true
  truthy:
    level: error
    # Allow only YAML 1.2 booleans https://redhat-cop.github.io/automation-good-practices/#_yaml_and_jinja2_syntax
    allowed-values:
      - 'true'
      - 'false'
  document-end: disable
...
