---
name: ROSA EE build

on:  # yamllint disable-line rule:truthy
  push:
    branches:
      - 'main'
    paths:
      - 'rosa-ee/**'
      - '.github/workflows/rosa-ee-build.yml'
      - '.github/workflows/deploy-ee.yml'
      - 'ansible.cfg'
      - 'requirements.txt'

  schedule:
    - cron: '0 0 * * 0'

  # Allow manual run from the Actions tab
  workflow_dispatch:

jobs:
  call-deploy-workflow:
    uses: branic/ansible-ee-builds/.github/workflows/deploy-ee.yml@main
    with:
      EE_FOLDER_NAME: 'rosa-ee'
      EE_IMAGE_TAG: 'latest'
    secrets:
      QUAY_USERNAME: ${{ secrets.QUAY_USERNAME}}
      QUAY_PASSWORD: ${{ secrets.QUAY_PASSWORD }}
      REDHAT_USERNAME: ${{ secrets.REDHAT_USERNAME }}
      REDHAT_PASSWORD: ${{ secrets.REDHAT_PASSWORD }}
      AH_TOKEN: ${{ secrets.AH_TOKEN }}
